import React,{useEffect} from 'react';
import {MapContainer,TileLayer,Marker,CircleMarker,Circle,Popup,Tooltip,useMap,useMapEvents} from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import 'leaflet.heat';
const sosIcon=L.divIcon({className:'sos-map-icon',html:'<span>SOS</span>',iconSize:[40,40],iconAnchor:[20,20]});
export const COLORS={high:'#e34939',medium:'#ed9635',low:'#d7b638',closed:'#85909e'};
function Heat({points,on}){const map=useMap();useEffect(()=>{if(!on||!points.length)return;const layer=L.heatLayer(points,{radius:32,blur:24,maxZoom:15,gradient:{.2:'#3b82f6',.5:'#facc15',.8:'#f97316',1:'#ef4444'}}).addTo(map);return()=>layer.remove()},[map,points,on]);return null}
function Events({onPick,focus}){const map=useMap();useMapEvents({click:e=>onPick?.({lat:e.latlng.lat,lng:e.latlng.lng,source:'pin'})});useEffect(()=>{if(focus)map.flyTo([focus.lat,focus.lng],Math.max(map.getZoom(),14),{duration:.6})},[focus?.lat,focus?.lng]);useEffect(()=>{const timer=setTimeout(()=>map.invalidateSize(),200);return()=>clearTimeout(timer)},[map]);return null}
export default function MapView({items=[],environment=[],heat=[],heatOn=false,hazards=true,select,onPick,point,focus,areas=[]}){
 return <MapContainer center={[27.704,85.322]} zoom={12} scrollWheelZoom={false} className="map-canvas"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://tile.openstreetmap.org/{z}/{x}/{y}.png"/><Events onPick={onPick} focus={focus||point}/><Heat points={heat} on={heatOn}/>{areas.map(a=><CircleMarker key={a.name} center={[a.lat,a.lng]} radius={3} pathOptions={{color:'#687d88',fillOpacity:1}}><Tooltip permanent direction="right" className="area-label">{a.name}</Tooltip></CircleMarker>)}{hazards&&environment.filter(e=>['high','critical'].includes(e.risk_level)&&Date.now()/1000-e.observed_at<10800).map(e=><Circle key={e.id} center={[e.lat,e.lng]} radius={e.event_type==='landslide_assessment'?650:1000} pathOptions={{color:e.event_type==='temperature'?'#3986ac':e.event_type==='rainfall'?'#557ecc':'#d58528',weight:1,dashArray:'5 5',fillOpacity:.09}}><Popup>{e.is_simulated&&'SIMULATED · '}{e.event_type}: {e.value} · {e.risk_level}<br/>Illustrative marker, not a mapped hazard boundary. Context applies within 10 km.</Popup></Circle>)}{items.map(i=>i.is_sos?<Marker key={i.id} position={[i.lat,i.lng]} icon={sosIcon} eventHandlers={{click:()=>select?.(i.id)}}><Tooltip>SOS · {i.place_name} · {i.status}</Tooltip></Marker>:<CircleMarker key={i.id} center={[i.lat,i.lng]} radius={i.audio_count?12:9} pathOptions={{color:'white',weight:3,fillColor:COLORS[['resolved','false_alarm'].includes(i.status)?'closed':i.priority],fillOpacity:1}} eventHandlers={{click:()=>select?.(i.id)}}><Tooltip>{i.place_name} · {i.score} evidence points {i.audio_count?'· audio':''}</Tooltip></CircleMarker>)}{point&&<CircleMarker center={[point.lat,point.lng]} radius={9} pathOptions={{color:'#163f61',fillColor:'#f04b3a',fillOpacity:1,weight:3}}/>}</MapContainer>
}
