import React,{useEffect,useRef,useState} from 'react';
import {Camera,Square,Upload,ScanLine} from 'lucide-react';
import jsQR from 'jsqr';
import {parsePersonCode} from './registry';

export default function QRScanner({onCode,notify}){
 const video=useRef(null),stream=useRef(null),frame=useRef(null),active=useRef(false);
 const [running,setRunning]=useState(false),[code,setCode]=useState('');
 function stop(){active.current=false;cancelAnimationFrame(frame.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null;setRunning(false)}
 useEffect(()=>()=>{active.current=false;cancelAnimationFrame(frame.current);stream.current?.getTracks().forEach(t=>t.stop())},[]);
 function accept(text){const id=parsePersonCode(text);if(!id){notify('Use a ResQ person ID or its QR code.');return}setCode(id);onCode(id)}
 async function start(){try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});active.current=true;setRunning(true);video.current.srcObject=stream.current;await video.current.play();const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});let last=0;function tick(now){if(!active.current)return;if(now-last>200&&video.current?.readyState>=2){last=now;canvas.width=video.current.videoWidth;canvas.height=video.current.videoHeight;ctx.drawImage(video.current,0,0);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height);const result=jsQR(pixels.data,canvas.width,canvas.height);if(result&&parsePersonCode(result.data)){stop();accept(result.data);return}}frame.current=requestAnimationFrame(tick)}frame.current=requestAnimationFrame(tick)}catch{stop();notify('Camera unavailable. Upload a QR image or paste the ID instead.')}}
 async function image(e){const file=e.target.files[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error('Choose a QR image under 5 MB.');const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));canvas.width=bitmap.width*scale;canvas.height=bitmap.height*scale;ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const pixels=ctx.getImageData(0,0,canvas.width,canvas.height),result=jsQR(pixels.data,canvas.width,canvas.height);if(!result)throw Error('No readable QR code found. Try a clearer image.');accept(result.data)}catch(err){notify(err.message)}e.target.value=''}
 return <div className="scanner-block"><div className="scan-actions"><button type="button" className="primary" onClick={running?stop:start}>{running?<Square size={17}/>:<Camera size={17}/>} {running?'Stop camera':'Scan QR with camera'}</button><label className="secondary qr-upload"><Upload size={16}/> Upload QR image<input type="file" accept="image/*" onChange={image}/></label></div><video ref={video} muted playsInline hidden={!running} className="qr-video"/><form className="id-lookup" onSubmit={e=>{e.preventDefault();accept(code)}}><label htmlFor="person-code">Person ID / scanner input</label><div><input id="person-code" value={code} onChange={e=>setCode(e.target.value)} placeholder="P-… or RESQ:P-…" autoComplete="off"/><button className="secondary"><ScanLine size={16}/> Open profile</button></div></form><p className="field-help">Scanning opens a profile. Review the selected site and status, then confirm check-in. Camera images stay on this device.</p></div>
}
