import React,{useState,useRef,useEffect} from 'react';
import {Siren,X,MapPin,CheckCircle2} from 'lucide-react';
import {api} from './api';
import {useApp,LocationPicker} from './common';
import './sos.css';
export default function SOS({onReceived}){
 const {session}=useApp();const [open,setOpen]=useState(false),[point,setPoint]=useState(null),[locating,setLocating]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState(null),[coords,setCoords]=useState({lat:'',lng:''});
 const request=useRef(null),sending=useRef(false),gpsGeneration=useRef(0),box=useRef(null),trigger=useRef(null);
 useEffect(()=>()=>{gpsGeneration.current++},[]);
 useEffect(()=>{if(!open)return;const before=document.activeElement;box.current?.focus();const previous=document.body.style.overflow;document.body.style.overflow='hidden';const key=e=>{if(e.key==='Escape'&&!sending.current)close();if(e.key==='Tab'){const nodes=box.current.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),a[href]');const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===box.current)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',key);before?.focus()}},[open]);
 function close(){if(sending.current)return;gpsGeneration.current++;setLocating(false);setOpen(false)}
 function choose(p){gpsGeneration.current++;setLocating(false);setPoint(p);setError('')}
 function start(){setOpen(true);if(request.current||receipt)return;setError('');setLocating(true);const generation=++gpsGeneration.current;if(!navigator.geolocation){setLocating(false);setError('GPS is unavailable. Select a map location or enter coordinates.');return}navigator.geolocation.getCurrentPosition(p=>{if(generation!==gpsGeneration.current)return;setPoint({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,source:'gps'});setLocating(false)},e=>{if(generation!==gpsGeneration.current)return;setLocating(false);setError(e.code===1?'Location permission denied. Select a map location or enter coordinates.':'GPS could not find your position. Select a map location or enter coordinates.')},{enableHighAccuracy:true,timeout:12000,maximumAge:0})}
 function manual(){const lat=Number(coords.lat),lng=Number(coords.lng);if(!coords.lat.trim()||!coords.lng.trim()||!Number.isFinite(lat)||!Number.isFinite(lng)||Math.abs(lat)>90||Math.abs(lng)>180){setError('Enter latitude between −90 and 90 and longitude between −180 and 180.');return}choose({lat,lng,source:'manual'})}
 async function send(){if(sending.current||receipt||!point)return;sending.current=true;setBusy(true);setError('');gpsGeneration.current++;setLocating(false);
 request.current||={client_id:crypto.randomUUID(),lat:point.lat,lng:point.lng,location_source:point.source,accuracy:point.accuracy??null,timestamp:Date.now()/1000,emergency_status:'sos'};
 try{const result=await api('/sos',{method:'POST',body:JSON.stringify(request.current)});if(!result.received)throw Error('The server did not confirm receipt. Retry this SOS.');setReceipt(result);request.current=null;try{await onReceived()}catch{/* Receipt is valid even if responder dashboard refresh fails. */}}
 catch(e){setError(e.status===429?'Too many requests. Wait one minute, then retry this same SOS.':e.network||e.retryable?'Receipt could not be confirmed. Check your connection and retry this same SOS; retries cannot create another incident.':e.message)}finally{sending.current=false;setBusy(false)}}
 return <><div className="sos-entry"><div><Siren size={19}/><span><strong>Emergency assistance</strong><small>Share your location with response coordinators.</small></span></div><button ref={trigger} className="sos-button" onClick={start}><Siren size={19}/>{receipt?'SOS RECEIVED':'SEND SOS'}</button></div>{open&&<div className="drawer-overlay sos-overlay"><section className="sos-dialog" role="dialog" aria-modal="true" aria-labelledby="sos-title" tabIndex={-1} ref={box}><div className="sos-dialog-top"><span><Siren size={20}/> EMERGENCY SOS</span><button className="icon-button" disabled={busy} onClick={close} aria-label="Close SOS"><X size={20}/></button></div>{receipt?<div className="sos-body"><CheckCircle2 size={34}/><h2 id="sos-title">SOS received by the server</h2><p>Your alert is saved for responder review. This does not confirm that rescuers have been dispatched.</p><code>{receipt.id}</code><p>Received: {new Date(receipt.received_at*1000).toLocaleString()}</p>{session&&<a className="secondary" href={'/?report='+encodeURIComponent(receipt.id)}>View SOS in Command Center</a>}<button className="secondary" onClick={close}>Close</button><button className="quiet" onClick={()=>{setReceipt(null);setPoint(null);setOpen(false)}}>Start a separate emergency alert</button></div>:<div className="sos-body"><h2 id="sos-title">Confirm your emergency location</h2><p>Only authorized responders can view the submitted coordinates. Your location is sent only when you confirm below.</p>{locating&&<p role="status">Finding your GPS location… You can also select it manually.</p>}{error&&<div className="sos-error" role="alert">{error}</div>}<fieldset disabled={busy||!!request.current}><LocationPicker value={point} onChange={choose}/><details><summary>Enter latitude and longitude manually</summary><div className="two-fields"><label>Latitude<input type="number" min="-90" max="90" step="any" value={coords.lat} onChange={e=>setCoords({...coords,lat:e.target.value})}/></label><label>Longitude<input type="number" min="-180" max="180" step="any" value={coords.lng} onChange={e=>setCoords({...coords,lng:e.target.value})}/></label></div><button type="button" className="secondary" onClick={manual}>Use these coordinates</button></details></fieldset>{point&&<div className="sos-location"><MapPin size={16}/><span>{point.lat}, {point.lng}{point.accuracy!=null&&<small>GPS accuracy approximately ±{Math.round(point.accuracy)} m. Adjust the pin if needed.</small>}</span></div>}<p className="field-help">Send a high-priority request for assistance at this location? No automatic dispatch. If the internet is unavailable, use your local emergency contact.</p><button className="sos-button" disabled={busy||!point} onClick={send}><Siren size={18}/>{busy?'Sending SOS…':request.current?'Retry this SOS':'Confirm & send SOS'}</button><button className="secondary" disabled={busy} onClick={close}>Cancel</button></div>}</section></div>}</>
}
